services:
  - type: web
    name: ravon-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PING_URL
        sync: false
      - key: TEACHER_IDS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DB_NAME
        value: "ravon_ai.db"
      - key: REQUIRED_CHANNEL
        value: "@englishwithSanatbek"
      - key: REQUIRED_CHANNEL_ID
        value: "-1003014655042"
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: ravon-data
      mountPath: /data
      sizeGB: 1
