services:
  - type: web
    name: ravon-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd /opt/render/project && python -m src.main
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PING_URL
        sync: false
      - key: TEACHER_IDS
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DB_NAME
        value: "/data/ravon_ai.db"
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: ravon-data
      mountPath: /data
      sizeGB: 1
